#' @title prism_defs
#' @description A variable definition data.frame for a data frame produced by
#'   \code{prism_data}.
#' @return A data frame giving a theoretical classification of variables
#'   produced by \code{prism_data}.
#' @export
prism_defs <- function() {
  tibble::tribble(
    ~Group     , ~N, ~DENS, ~ELEV, ~GRAV, ~LX, ~LY, ~LZ, ~VX, ~VY, ~VZ, ~Add, ~Mult, ~Exp, ~Variable     , ~Measure.Description                                               , ~Units  , ~Type.Calculation                                                        ,
    "density"  ,  1,  0   ,  1   ,  1   ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1  ,  1   ,  1  , "DENSITY"     , "kilograms per cubic meter (kg / m^3)"                             , "kg/m^3", "fundamental: DENSITY + ~N(0, 0.01)"                                     ,
    "elevation",  1,  1   ,  0   ,  1   ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1  ,  1   ,  1  , "ELEVATION"   , "elevation above ground level (i.e., position on z-axis [m])"      , "m"     , "fundamental: ELEVATION + ~N(0, 0.01)"                                   ,
    "gravity"  ,  1,  1   ,  1   ,  0   ,  1 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1  ,  1   ,  1  , "GRAVITY"     , "gravity (acceleration) along the z-axis in m/s/s)"                , "m/s^2" , "fundamental: GRAVITY + ~N(0, 0.01)"                                     ,
    "length"   ,  1,  1   ,  1   ,  1   ,  0 ,  1 ,  1 ,  1 ,  1 ,  1 ,  1  ,  1   ,  1  , "LENGTH.X"    , "length of edge oriented along the x axis (m)"                     , "m"     , "fundamental: LENGTH.X + ~N(0, 0.01)"                                    ,
    "length"   ,  1,  1   ,  1   ,  1   ,  1 ,  0 ,  1 ,  1 ,  1 ,  1 ,  1  ,  1   ,  1  , "LENGTH.Y"    , "length of edge oriented along the y axis (m)"                     , "m"     , "fundamental: LENGTH.Y + ~N(0, 0.01)"                                    ,
    "length"   ,  1,  1   ,  1   ,  1   ,  1 ,  1 ,  0 ,  1 ,  1 ,  1 ,  1  ,  1   ,  1  , "LENGTH.Z"    , "length of edge oriented along the z axis (m)"                     , "m"     , "fundamental: LENGTH.Z + ~N(0, 0.01)"                                    ,
    "velocity" ,  1,  1   ,  1   ,  1   ,  1 ,  1 ,  1 ,  0 ,  1 ,  1 ,  1  ,  1   ,  1  , "VELOCITY.X"  , "1-D velocity component along the line defined by the x-axis (m/s)", "m/s"   , "fundamental: VELOCITY.X + ~N(0, 0.01)"                                  ,
    "velocity" ,  1,  1   ,  1   ,  1   ,  1 ,  1 ,  1 ,  1 ,  0 ,  1 ,  1  ,  1   ,  1  , "VELOCITY.Y"  , "1-D velocity component along the line defined by the y-axis (m/s)", "m/s"   , "fundamental: VELOCITY.Y + ~N(0, 0.01)"                                  ,
    "velocity" ,  1,  1   ,  1   ,  1   ,  1 ,  1 ,  1 ,  1 ,  1 ,  0 ,  1  ,  1   ,  1  , "VELOCITY.Z"  , "1-D velocity component along the line defined by the z-axis (m/s)", "m/s"   , "fundamental: VELOCITY.Z + ~N(0, 0.01)"                                  ,
    "area"     ,  2,  1   ,  1   ,  1   ,  0 ,  0 ,  1 ,  1 ,  1 ,  1 ,  1  ,  0   ,  1  , "area.xy"     , "area of x-y face (m^2)"                                           , "m^2"   , "derived: LENGTH.X × LENGTH.Y + ~N(0, 0.01)"                             ,
    "area"     ,  2,  1   ,  1   ,  1   ,  0 ,  1 ,  0 ,  1 ,  1 ,  1 ,  1  ,  0   ,  1  , "area.xz"     , "area of x-z face (m^2)"                                           , "m^2"   , "derived: LENGTH.X × LENGTH.Z + ~N(0, 0.01)"                             ,
    "area"     ,  2,  1   ,  1   ,  1   ,  1 ,  0 ,  0 ,  1 ,  1 ,  1 ,  1  ,  0   ,  1  , "area.yz"     , "area of y-z face (m^2)"                                           , "m^2"   , "derived: LENGTH.Y × LENGTH.Z + ~N(0, 0.01)"                             ,
    "area"     ,  3,  1   ,  1   ,  1   ,  0 ,  0 ,  0 ,  1 ,  1 ,  1 ,  1  ,  0   ,  1  , "area.surface", "surface area (m^2)"                                               , "m^2"   , "derived: 2 × (area.xy + area.xz + area.yz) + ~N(0, 0.01)"               ,
    "length"   ,  2,  1   ,  1   ,  1   ,  0 ,  0 ,  1 ,  1 ,  1 ,  1 ,  0  ,  1   ,  0  , "diag.xy"     , "length of diagonal of the x-y face (m)"                           , "m"     , "derived: sqrt(LENGTH.X^2 + LENGTH.Y^2) + ~N(0, 0.01)"                   ,
    "length"   ,  2,  1   ,  1   ,  1   ,  0 ,  1 ,  0 ,  1 ,  1 ,  1 ,  0  ,  1   ,  0  , "diag.xz"     , "length of diagonal of the x-z face (m)"                           , "m"     , "derived: sqrt(LENGTH.X^2 + LENGTH.Z^2) + ~N(0, 0.01)"                   ,
    "length"   ,  2,  1   ,  1   ,  1   ,  1 ,  0 ,  0 ,  1 ,  1 ,  1 ,  0  ,  1   ,  0  , "diag.yz"     , "length of diagonal of the y-z face (m)"                           , "m"     , "derived: sqrt(LENGTH.Y^2 + LENGTH.Z^2) + ~N(0, 0.01)"                   ,
    "length"   ,  3,  1   ,  1   ,  1   ,  0 ,  0 ,  0 ,  1 ,  1 ,  1 ,  0  ,  1   ,  0  , "diag.xyz"    , "length of internal diagonal (m)"                                  , "m"     , "derived: sqrt(LENGTH.X^2 + LENGTH.Y^2 + LENGTH.Z^2) + ~N(0, 0.01)"      ,
    "length"   ,  2,  1   ,  1   ,  1   ,  0 ,  0 ,  1 ,  1 ,  1 ,  1 ,  0  ,  1   ,  1  , "circ.xy"     , "circumference of the x-y face (m)"                                , "m"     , "derived: 2 × (LENGTH.X + LENGTH.Y) + ~N(0, 0.01)"                       ,
    "length"   ,  2,  1   ,  1   ,  1   ,  0 ,  1 ,  0 ,  1 ,  1 ,  1 ,  0  ,  1   ,  1  , "circ.xz"     , "circumference of the x-z face (m)"                                , "m"     , "derived: 2 × (LENGTH.X + LENGTH.Z) + ~N(0, 0.01)"                       ,
    "length"   ,  2,  1   ,  1   ,  1   ,  1 ,  0 ,  0 ,  1 ,  1 ,  1 ,  0  ,  1   ,  1  , "circ.yz"     , "circumference of the y-z face (m)"                                , "m"     , "derived: 2 × (LENGTH.Y + LENGTH.Z) + ~N(0, 0.01)"                       ,
    "length"   ,  3,  1   ,  1   ,  1   ,  0 ,  0 ,  0 ,  1 ,  1 ,  1 ,  0  ,  1   ,  1  , "circ.xyz"    , "length of all edges"                                              , "m"     , "derived: 4 × (LENGTH.X + LENGTH.Y + LENGTH.Z) + ~N(0, 0.01)"            ,
    "velocity" ,  2,  1   ,  1   ,  1   ,  1 ,  1 ,  1 ,  0 ,  0 ,  1 ,  1  ,  0   ,  0  , "velocity.xy" , "2-D velocity along the plane defined by an x-y face (m/s)"        , "m/s"   , "derived: sqrt(VELOCITY.X^2 + VELOCITY.Y^2) + ~N(0, 0.01)"               ,
    "velocity" ,  2,  1   ,  1   ,  1   ,  1 ,  1 ,  1 ,  0 ,  1 ,  0 ,  1  ,  0   ,  0  , "velocity.xz" , "2-D velocity along the plane defined by an x-z face (m/s)"        , "m/s"   , "derived: sqrt(VELOCITY.X^2 + VELOCITY.Z^2) + ~N(0, 0.01)"               ,
    "velocity" ,  2,  1   ,  1   ,  1   ,  1 ,  1 ,  1 ,  1 ,  0 ,  0 ,  1  ,  0   ,  0  , "velocity.yz" , "2-D velocity along the plane defined by an y-z face (m/s)"        , "m/s"   , "derived: sqrt(VELOCITY.Y^2 + VELOCITY.Z^2) + ~N(0, 0.01)"               ,
    "velocity" ,  3,  1   ,  1   ,  1   ,  1 ,  1 ,  1 ,  0 ,  0 ,  0 ,  1  ,  0   ,  0  , "velocity.xyz", "3-D total velocity (m/s)"                                         , "m/s"   , "derived: sqrt(VELOCITY.X^2 + VELOCITY.Y^2 + VELOCITY.Z^2) + ~N(0, 0.01)",
    "volume"   ,  3,  1   ,  1   ,  1   ,  0 ,  0 ,  0 ,  1 ,  1 ,  1 ,  1  ,  0   ,  1  , "volume"      , "volume (m^3)"                                                     , "m^3"   , "derived: LENGTH.X × LENGTH.Y × LENGTH.Z + ~N(0, 0.01)"                  ,
    "mass"     ,  4,  0   ,  1   ,  1   ,  0 ,  0 ,  0 ,  1 ,  1 ,  1 ,  1  ,  0   ,  1  , "mass"        , "mass in kilograms (kg)"                                           , "kg"    , "derived: DENSITY × volume + ~N(0, 0.01)"                                ,
    "energy"   ,  7,  0   ,  1   ,  1   ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0  ,  0   ,  0  , "kinetic"     , "kinetic energy (joules)"                                          , "joules", "derived: mass × velocity^2 + ~N(0, 0.01)"                               ,
    "energy"   ,  6,  0   ,  0   ,  0   ,  0 ,  0 ,  0 ,  1 ,  1 ,  1 ,  1  ,  0   ,  1  , "potential"   , "potential energy (joules)"                                        , "joules", "derived: mass × ELEVATION × GRAVITY + ~N(0, 0.01)"                      ,
    "energy"   ,  9,  0   ,  0   ,  0   ,  0 ,  0 ,  0 ,  0 ,  0 ,  0 ,  0  ,  0   ,  0  , "total"       , "total energy (joules)"                                            , "joules", "derived: kinetic + potential + ~N(0, 0.01)"
  )
}
